# Generated by Django 4.2.9 on 2024-02-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.FloatField(help_text='in minutes'),
        ),
    ]
