# Generated by Django 4.2.9 on 2024-02-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='recipes'),
        ),
    ]
